apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-eb2h
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-eb2h@sha256:962691b6991c9503ecff2e3e9108f4f8d14e92343bd86535af4463cb313a6297
        name: my-nodejs
        resources: {}
status: {}
